#!/bin/sh

URL="$1"
ARCHIVE=/media/music

logger -t youtube-play "play $URL"


cd $ARCHIVE

FILENAME=$(youtube-dl --get-filename -f bestaudio $URL)
logger -t youtube-play "FILENAME=$FILENAME"
youtube-dl -f bestaudio $URL

killall gst-play-1.0
gst-play-1.0 "$FILENAME"


